baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
[module]
[[module.imports]]
path = "github.com/hungryram/vesper"
[[module.mounts]]
source = "layout"
target = "layout"